import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import VlDeposit from '@/components/vlYcrv/vlDeposit'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  
  return (
    <>
      <Head>
        <title>SeaBeam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      
      
      <section className='max-w-7xl mx-auto px-8 sm:px-16'>
        <h1> Main Page</h1>
        <VlDeposit></VlDeposit>
      </section>
      

      
    </>
  )
}
